# Generated by Django 4.0.1 on 2022-05-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
